import Head from "next/head";
import Navigation from '../components/Navigation';

export default function Home() {

  return (
    <div className="h-screen w-screen p-10 dark:bg-gray-900 bg-indigo-200">
      <Head>
        <title>Adnan Ahmed portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}